# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\GIS\layout\ui\main_window.ui'
#
# Created: Wed Jan 15 21:38:45 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 723)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineColorCb = QtGui.QComboBox(self.groupBox)
        self.lineColorCb.setObjectName("lineColorCb")
        self.lineColorCb.addItem("")
        self.lineColorCb.addItem("")
        self.lineColorCb.addItem("")
        self.lineColorCb.addItem("")
        self.gridLayout.addWidget(self.lineColorCb, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.lineWidthCb = QtGui.QComboBox(self.groupBox)
        self.lineWidthCb.setObjectName("lineWidthCb")
        self.lineWidthCb.addItem("")
        self.lineWidthCb.addItem("")
        self.lineWidthCb.addItem("")
        self.lineWidthCb.addItem("")
        self.lineWidthCb.addItem("")
        self.gridLayout.addWidget(self.lineWidthCb, 0, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.nodeColorCb = QtGui.QComboBox(self.groupBox)
        self.nodeColorCb.setObjectName("nodeColorCb")
        self.nodeColorCb.addItem("")
        self.nodeColorCb.addItem("")
        self.nodeColorCb.addItem("")
        self.nodeColorCb.addItem("")
        self.gridLayout.addWidget(self.nodeColorCb, 0, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 6, 1, 1)
        self.nodeWidthCb = QtGui.QComboBox(self.groupBox)
        self.nodeWidthCb.setObjectName("nodeWidthCb")
        self.nodeWidthCb.addItem("")
        self.nodeWidthCb.addItem("")
        self.nodeWidthCb.addItem("")
        self.nodeWidthCb.addItem("")
        self.nodeWidthCb.addItem("")
        self.nodeWidthCb.addItem("")
        self.nodeWidthCb.addItem("")
        self.gridLayout.addWidget(self.nodeWidthCb, 0, 7, 1, 1)
        self.graphicsView = QtGui.QGraphicsView(self.groupBox)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 8)
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 30))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionKruskal = QtGui.QAction(MainWindow)
        self.actionKruskal.setObjectName("actionKruskal")
        self.actionNext = QtGui.QAction(MainWindow)
        self.actionNext.setObjectName("actionNext")
        self.actionSave_graph = QtGui.QAction(MainWindow)
        self.actionSave_graph.setObjectName("actionSave_graph")
        self.actionOpen_from_file = QtGui.QAction(MainWindow)
        self.actionOpen_from_file.setObjectName("actionOpen_from_file")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionOpen_from_file_weight = QtGui.QAction(MainWindow)
        self.actionOpen_from_file_weight.setObjectName("actionOpen_from_file_weight")
        self.actionExport_weights = QtGui.QAction(MainWindow)
        self.actionExport_weights.setObjectName("actionExport_weights")
        self.actionPRIMA = QtGui.QAction(MainWindow)
        self.actionPRIMA.setObjectName("actionPRIMA")
        self.actionNext_Prima = QtGui.QAction(MainWindow)
        self.actionNext_Prima.setObjectName("actionNext_Prima")
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionExport_weights)
        self.menuFile.addAction(self.actionOpen_from_file)
        self.menuFile.addAction(self.actionOpen_from_file_weight)
        self.menuFile.addAction(self.actionSave_graph)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionKruskal)
        self.toolBar.addAction(self.actionPRIMA)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Minimal spanning tree", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Line color", None, QtGui.QApplication.UnicodeUTF8))
        self.lineColorCb.setItemText(0, QtGui.QApplication.translate("MainWindow", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.lineColorCb.setItemText(1, QtGui.QApplication.translate("MainWindow", "grey", None, QtGui.QApplication.UnicodeUTF8))
        self.lineColorCb.setItemText(2, QtGui.QApplication.translate("MainWindow", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.lineColorCb.setItemText(3, QtGui.QApplication.translate("MainWindow", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Line width", None, QtGui.QApplication.UnicodeUTF8))
        self.lineWidthCb.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineWidthCb.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.lineWidthCb.setItemText(2, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.lineWidthCb.setItemText(3, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.lineWidthCb.setItemText(4, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Node color", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeColorCb.setItemText(0, QtGui.QApplication.translate("MainWindow", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeColorCb.setItemText(1, QtGui.QApplication.translate("MainWindow", "gray", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeColorCb.setItemText(2, QtGui.QApplication.translate("MainWindow", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeColorCb.setItemText(3, QtGui.QApplication.translate("MainWindow", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Node width", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(0, QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(1, QtGui.QApplication.translate("MainWindow", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(2, QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(3, QtGui.QApplication.translate("MainWindow", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(4, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(5, QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(6, QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKruskal.setText(QtGui.QApplication.translate("MainWindow", "Kruskal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKruskal.setToolTip(QtGui.QApplication.translate("MainWindow", "Kruskall algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setToolTip(QtGui.QApplication.translate("MainWindow", "Next step", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_graph.setText(QtGui.QApplication.translate("MainWindow", "Save to image file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_from_file.setText(QtGui.QApplication.translate("MainWindow", "Import nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("MainWindow", "Export nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_from_file_weight.setText(QtGui.QApplication.translate("MainWindow", "Import weights", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_weights.setText(QtGui.QApplication.translate("MainWindow", "Export weights", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPRIMA.setText(QtGui.QApplication.translate("MainWindow", "Prim", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Prima.setText(QtGui.QApplication.translate("MainWindow", "Next Prima", None, QtGui.QApplication.UnicodeUTF8))

