# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Mon Jan 13 23:39:32 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 729)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineColorCb = QtGui.QComboBox(self.groupBox)
        self.lineColorCb.setGeometry(QtCore.QRect(150, 0, 78, 24))
        self.lineColorCb.setObjectName("lineColorCb")
        self.lineColorCb.addItem("")
        self.lineColorCb.addItem("")
        self.lineColorCb.addItem("")
        self.lineColorCb.addItem("")
        self.lineWidthCb = QtGui.QComboBox(self.groupBox)
        self.lineWidthCb.setGeometry(QtCore.QRect(300, 0, 78, 24))
        self.lineWidthCb.setObjectName("lineWidthCb")
        self.lineWidthCb.addItem("")
        self.lineWidthCb.addItem("")
        self.lineWidthCb.addItem("")
        self.lineWidthCb.addItem("")
        self.lineWidthCb.addItem("")
        self.nodeColorCb = QtGui.QComboBox(self.groupBox)
        self.nodeColorCb.setGeometry(QtCore.QRect(470, 0, 78, 24))
        self.nodeColorCb.setObjectName("nodeColorCb")
        self.nodeColorCb.addItem("")
        self.nodeColorCb.addItem("")
        self.nodeColorCb.addItem("")
        self.nodeColorCb.addItem("")
        self.nodeWidthCb = QtGui.QComboBox(self.groupBox)
        self.nodeWidthCb.setGeometry(QtCore.QRect(640, 0, 78, 24))
        self.nodeWidthCb.setObjectName("nodeWidthCb")
        self.nodeWidthCb.addItem("")
        self.nodeWidthCb.addItem("")
        self.nodeWidthCb.addItem("")
        self.nodeWidthCb.addItem("")
        self.nodeWidthCb.addItem("")
        self.nodeWidthCb.addItem("")
        self.nodeWidthCb.addItem("")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(230, 0, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(80, 0, 58, 14))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(560, 0, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(390, 0, 71, 16))
        self.label_4.setObjectName("label_4")
        self.graphicsView = QtGui.QGraphicsView(self.groupBox)
        self.graphicsView.setGeometry(QtCore.QRect(-10, 30, 827, 626))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 30))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.insertToolBarBreak(self.toolBar)
        self.actionKruskal = QtGui.QAction(MainWindow)
        self.actionKruskal.setObjectName("actionKruskal")
        self.actionNext = QtGui.QAction(MainWindow)
        self.actionNext.setObjectName("actionNext")
        self.actionSave_graph = QtGui.QAction(MainWindow)
        self.actionSave_graph.setObjectName("actionSave_graph")
        self.actionOpen_from_file = QtGui.QAction(MainWindow)
        self.actionOpen_from_file.setObjectName("actionOpen_from_file")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionOpen_from_file_weight = QtGui.QAction(MainWindow)
        self.actionOpen_from_file_weight.setObjectName("actionOpen_from_file_weight")
        self.actionExport_weights = QtGui.QAction(MainWindow)
        self.actionExport_weights.setObjectName("actionExport_weights")
        self.actionPRIMA = QtGui.QAction(MainWindow)
        self.actionPRIMA.setObjectName("actionPRIMA")
        self.actionNext_Prima = QtGui.QAction(MainWindow)
        self.actionNext_Prima.setObjectName("actionNext_Prima")
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionExport_weights)
        self.menuFile.addAction(self.actionOpen_from_file)
        self.menuFile.addAction(self.actionOpen_from_file_weight)
        self.menuFile.addAction(self.actionSave_graph)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionKruskal)
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPRIMA)
        self.toolBar.addAction(self.actionNext_Prima)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.lineColorCb.setItemText(0, QtGui.QApplication.translate("MainWindow", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.lineColorCb.setItemText(1, QtGui.QApplication.translate("MainWindow", "grey", None, QtGui.QApplication.UnicodeUTF8))
        self.lineColorCb.setItemText(2, QtGui.QApplication.translate("MainWindow", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.lineColorCb.setItemText(3, QtGui.QApplication.translate("MainWindow", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.lineWidthCb.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineWidthCb.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.lineWidthCb.setItemText(2, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.lineWidthCb.setItemText(3, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.lineWidthCb.setItemText(4, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeColorCb.setItemText(0, QtGui.QApplication.translate("MainWindow", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeColorCb.setItemText(1, QtGui.QApplication.translate("MainWindow", "gray", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeColorCb.setItemText(2, QtGui.QApplication.translate("MainWindow", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeColorCb.setItemText(3, QtGui.QApplication.translate("MainWindow", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(0, QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(1, QtGui.QApplication.translate("MainWindow", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(2, QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(3, QtGui.QApplication.translate("MainWindow", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(4, QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(5, QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeWidthCb.setItemText(6, QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Line width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Line color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Node width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Node color", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKruskal.setText(QtGui.QApplication.translate("MainWindow", "Kruskal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKruskal.setToolTip(QtGui.QApplication.translate("MainWindow", "Kruskall algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setToolTip(QtGui.QApplication.translate("MainWindow", "Next step", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_graph.setText(QtGui.QApplication.translate("MainWindow", "Save to image file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_from_file.setText(QtGui.QApplication.translate("MainWindow", "Import nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("MainWindow", "Export nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_from_file_weight.setText(QtGui.QApplication.translate("MainWindow", "Import weights", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_weights.setText(QtGui.QApplication.translate("MainWindow", "Export weights", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPRIMA.setText(QtGui.QApplication.translate("MainWindow", "PRIMA", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext_Prima.setText(QtGui.QApplication.translate("MainWindow", "Next Prima", None, QtGui.QApplication.UnicodeUTF8))

